version: "3.8"

networks:
  default:
     name: Net
     driver: bridge
     ipam:
      config:
        - subnet: 10.0.8.0/16

services:
  redis:
    image: "redis"
    container_name: 'redis-server'
    hostname: redis
    ports:
      - "6379:6379"
  mp3download:
    restart: always
    depends_on:
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    image: mp3download:latest
    container_name: 'mp3download'
    volumes:
      - ./data:/usr/src/music/data
      - ./scripts:/usr/src/music/app
    entrypoint: /usr/src/music/app/init.sh
    ports:
      - 31521:5000
